local M = {}

local sym = require("ajf.utils").get_settings().symbols

--- Diagnostic severities.
M.icons = {
	diagnostics = {
		ERROR = sym.error,
		WARN = sym.warn,
		HINT = sym.hint,
		INFO = sym.info,
	},

	--- For folding.
	arrows = {
		right = "",
		left = "",
		up = "",
		down = "",
	},
	--- LSP symbol kinds.
	symbol_kinds = {
		Color = { icon = "󰏘", hl = "Normal" },
		Folder = { icon = "󰉋", hl = "Normal" },
		Keyword = { icon = "󰌋", hl = "Function" },
		Reference = { icon = "󰈇", hl = "Normal" },
		Snippet = { icon = "", hl = "Normal" },
		Text = { icon = "", hl = "Normal" },
		Unit = { icon = "", hl = "Normal" },
		Value = { icon = "󰎠", hl = "Normal" },
		File = { icon = "󰈙", hl = "Identifier" },
		Module = { icon = "󰆧", hl = "Include" },
		Namespace = { icon = "󰅪", hl = "Include" },
		Package = { icon = "󰏗", hl = "Include" },
		Class = { icon = "", hl = "Type" },
		Method = { icon = "ƒ", hl = "Function" },
		Property = { icon = "󰜢", hl = "Identifier" },
		Field = { icon = "", hl = "@field" },
		Constructor = { icon = "", hl = "@constructor" },
		Enum = { icon = "", hl = "Number" },
		Interface = { icon = "", hl = "Type" },
		Function = { icon = "󰊕", hl = "Function" },
		Variable = { icon = "󰀫", hl = "Variable" },
		Constant = { icon = "󰏿", hl = "Constant" },
		String = { icon = "", hl = "String" },
		Number = { icon = "#", hl = "Number" },
		Boolean = { icon = "⊨", hl = "Boolean" },
		Array = { icon = "󰅪", hl = "@constructor" },
		Object = { icon = "⦿", hl = "Type" },
		Key = { icon = "🔐", hl = "Type" },
		Null = { icon = "NULL", hl = "Type" },
		EnumMember = { icon = "", hl = "Number" },
		Struct = { icon = "󰙅", hl = "Structure" },
		Event = { icon = "", hl = "Type" },
		FCall = { icon = "󰅲", hl = "Function" },
		Operator = { icon = "󰆕", hl = "Operator" },
		TypeParameter = { icon = "𝙏", hl = "Identifier" },
		Component = { icon = "󰅴", hl = "Function" },
		Fragment = { icon = "󰅴", hl = "Constant" },
		TypeAlias = { icon = "", hl = "Type" },
		Parameter = { icon = "", hl = "Parameter" },
		StaticMethod = { icon = "", hl = "Function" },
		Macro = { icon = "", hl = "Function" },
		Heading = { icon = "󰉴", hl = "Keyword" },
	},

	iconkinds = {
		color = { icon = "󰏘", hl = "Normal" },
		folder = { icon = "󰉋", hl = "Normal" },
		keyword = { icon = "󰌋", hl = "Function" },
		reference = { icon = "󰈇", hl = "Normal" },
		snippet = { icon = "", hl = "Normal" },
		text = { icon = "", hl = "Normal" },
		unit = { icon = "", hl = "Normal" },
		value = { icon = "󰎠", hl = "Normal" },
		file = { icon = "󰈙", hl = "Identifier" },
		module = { icon = "󰆧", hl = "Include" },
		namespace = { icon = "󰅪", hl = "Include" },
		package = { icon = "󰏗", hl = "Include" },
		class = { icon = "", hl = "Type" },
		method = { icon = "ƒ", hl = "Function" },
		property = { icon = "󰜢", hl = "Identifier" },
		field = { icon = "", hl = "@field" },
		constructor = { icon = "", hl = "@constructor" },
		enum = { icon = "", hl = "Number" },
		interface = { icon = "", hl = "Type" },
		["function"] = { icon = "󰊕", hl = "Function" },
		variable = { icon = "󰀫", hl = "Variable" },
		constant = { icon = "󰏿", hl = "Constant" },
		string = { icon = "", hl = "String" },
		number = { icon = "#", hl = "Number" },
		boolean = { icon = "⊨", hl = "Boolean" },
		array = { icon = "󰅪", hl = "@constructor" },
		object = { icon = "⦿", hl = "Type" },
		key = { icon = "🔐", hl = "Type" },
		null = { icon = "NULL", hl = "Type" },
		enumMember = { icon = "", hl = "Number" },
		struct = { icon = "󰙅", hl = "Structure" },
		event = { icon = "", hl = "Type" },
		fCall = { icon = "󰅲", hl = "Function" },
		operator = { icon = "󰆕", hl = "Operator" },
		typeParameter = { icon = "𝙏", hl = "Identifier" },
		component = { icon = "󰅴", hl = "Function" },
		fragment = { icon = "󰅴", hl = "Constant" },
		typeAlias = { icon = "", hl = "Type" },
		parameter = { icon = "", hl = "Parameter" },
		staticMethod = { icon = "", hl = "Function" },
		macro = { icon = "", hl = "Function" },
		heading = { icon = "󰉴", hl = "Keyword" },
	},

	--- Shared icons that don't really fit into a category.
	misc = {
		bug = "",
		dashed_bar = "┊",
		ellipsis = "…",
		git = "",
		palette = "󰏘",
		robot = "󰚩",
		search = "",
		terminal = "",
		toolbox = "󰦬",
		vertical_bar = "│",
	},
}

return M
